<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HotelBooking.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelBooking.Domain\HotelBooking.Domain.csproj" />
    <ProjectReference Include="..\HotelBooking.Contracts\HotelBooking.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>